language python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  jupyter nbextension enable --py widgetsnbextension --sys-prefix
# command to run tests
script:
  - pytest-notebook
