name: travis_anaconda_jupyter
channels:
- defaults
dependencies:
- python=3.6
- numpy==1.16.4
- matplotlib
- scikit-image==0.15.0
- scipy
- scikit-learn
- statsmodels
- ipywidgets
- jupyter==1.0
- pytest==3.1.3
